source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'mysql2'

gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'sass-rails', '~> 5.0'
gem 'searchlight'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
