## Uncomment and set this to only include directories you want to watch
directories %w(. lib spec)

## Uncomment to clear the screen before every task
clearing :on

guard :minitest do
  # with Minitest::Spec
  watch(%r{^spec/(.*)_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$})         { |m| "spec/#{m[1]}_spec.rb" }
  watch(%r{^spec/spec_helper\.rb$}) { 'spec' }
end
