source 'https://rubygems.org'

gem 'bundler'
gem 'rake'

gem 'lotusrb',       '0.4.0'
gem 'lotus-model',   '~> 0.4'


gem 'pg'

gem 'haml'

group :test do
  gem 'rspec'
  gem 'capybara'
end

group :production do
  # gem 'puma'
end
